baseURL = 'https://jeremi.codes'
languageCode = 'en-us'
title = 'jeremi.codes'
theme = 'jc'
Paginate = 10
disqusShortname = "jeremi-codes"

[params]
author = "Jeremi Kaczmarczyk"
description = "Software engineering blog"
title = 'jeremi.codes'

[markup]
[markup.highlight]
style = 'nord'
tabWidth = 4

[related]
threshold = 80.0
includeNewer = false
toLower = false

[[related.indices]]
name = "keywords"
weight = 100.0

[[related.indices]]
name = "date"
weight = 10.0

[deployment]

[[deployment.targets]]
name = "prod"
URL = "s3://jeremi.codes-root?region=eu-west-2"

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|js|css)$"
gzip = true