baseURL = 'https://jeremi.codes'
languageCode = 'en-us'
title = 'jeremi.codes'
theme = 'jc'

[params]
author = "Jeremi Kaczmarczyk"
description = "Software engineering blog"
title = 'jeremi.codes'

[markup]
[markup.highlight]
style = 'nord'
tabWidth = 4
